import { NextRequest, NextResponse } from "next/server";
import prisma from "@/lib/prisma";
import { getServerSession } from "next-auth";
import { authOptions } from "@/lib/auth";

const IEC_COLORS: Record<string, string> = {
  C4: "ff0000ff", // red
  C3: "ff8800ff", // orange
  C2: "0088ffff", // blue
  C1: "00cc44ff", // green
  UNC: "aa00aaff", // purple
};

export async function GET(
  _req: NextRequest,
  { params }: { params: Promise<{ id: string }> }
) {
  const { id } = await params;
  const session = await getServerSession(authOptions);
  if (!session) return NextResponse.json({ error: "Unauthorized" }, { status: 401 });

  const report = await prisma.report.findUnique({
    where: { id },
    include: {
      inspection: {
        include: {
          site: true,
          anomalies: { where: { lat: { not: null }, lng: { not: null } }, orderBy: { deltaTC: "desc" } },
        },
      },
    },
  });
  if (!report) return NextResponse.json({ error: "Not found" }, { status: 404 });

  const { anomalies, site } = report.inspection;

  const placemarks = anomalies.map((a) => `
  <Placemark>
    <name>${a.iecClass}: ${a.type}</name>
    <description><![CDATA[
      <b>IEC Class:</b> ${a.iecClass}<br/>
      <b>ΔT:</b> +${a.deltaTC.toFixed(1)}°C<br/>
      <b>T Anomaly:</b> ${a.tAnomalyC.toFixed(1)}°C<br/>
      <b>Location:</b> ${a.locationString || "—"}<br/>
      <b>Priority:</b> ${a.priority || "—"}<br/>
      <b>Modules:</b> ${a.modulesAffected}<br/>
      <b>Notes:</b> ${a.notes || "—"}
    ]]></description>
    <styleUrl>#style_${a.iecClass}</styleUrl>
    <Point>
      <coordinates>${a.lng},${a.lat},0</coordinates>
    </Point>
  </Placemark>`).join("\n");

  const styles = Object.entries(IEC_COLORS).map(([cls, color]) => `
  <Style id="style_${cls}">
    <IconStyle>
      <color>${color}</color>
      <scale>1.2</scale>
      <Icon><href>http://maps.google.com/mapfiles/kml/paddle/wht-circle.png</href></Icon>
    </IconStyle>
    <LabelStyle><scale>0.8</scale></LabelStyle>
  </Style>`).join("\n");

  const kml = `<?xml version="1.0" encoding="UTF-8"?>
<kml xmlns="http://www.opengis.net/kml/2.2">
  <Document>
    <name>NexPwr — ${site.name} Anomaly Map</name>
    <description>Generated by NexPwr by Elytrus Pvt. Ltd. | IEC 62446-3:2017</description>
    ${styles}
    ${placemarks}
  </Document>
</kml>`;

  return new NextResponse(kml, {
    status: 200,
    headers: {
      "Content-Type": "application/vnd.google-earth.kml+xml",
      "Content-Disposition": `attachment; filename="nexpwr-anomalies-${id.slice(0, 8)}.kml"`,
    },
  });
}
